### ISSUE TITLE
Feature Request: Pass className to animation

### ISSUE THREAD

**Issue by GeorgeWL** [bluebill1049/react-simple-animate#50]
I don't know if this is outside of the scope of this more lightweight module, but it would be nice if possible to allow one to set a `className` prop that applies a css class instead of using a style object.

**Comment by bluebill1049** [comment]
hey @GeorgeWL 

oh yeah, that's possible. but I guess that defeats the purpose of this little library because you are basically toggling the `className`. you can already do that in React.

I actually wrote a blog about it as well https://medium.com/jsdownunder/react-ui-animation-made-simple-c2ff98056659

but I am sure you have your reasons, I would love to hear your concern as well see if I can make something works for you as well :)

**Comment by GeorgeWL** [comment]
Yeah you've a point there tbh.

 Only reason for it I can think possibly is adding a class name only on
componentWillUnmount, but that's too much of an edge case and can be done
just as easily with changing the props for the animation instead.

Feel free to close it

Kind Regards,

George W Langham

**Comment by bluebill1049** [comment]
ha thanks for understanding @GeorgeWL feel free to leave more feedback in the future :)

have a good weekend 
bill

**Comment by GeorgeWL** [comment]
Yeah I had a feeling it may be out of scope

Kind Regards,

George W Langham
